<?php

declare(strict_types=1);

namespace App\Filament\Resources;

use App\Filament\Resources\ProductResource\Pages;
use App\Models\Product;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

/**
 * ProductResource — Filament 3 declarative admin CRUD for Products.
 *
 * This replaces the original AdminController declarative pattern (v6).
 * The form schema replaces $form_vars; the table columns replace $filters;
 * the pages (list, create, edit) are all generated by Filament.
 *
 * Includes: SEO tab (descriptions per language), store assignment tab,
 * categories tab, images tab, pricing tab.
 *
 * @see v6 (AdminController declarative CRUD)
 * @see v12 (pattern 2: AdminController -> Filament Resources)
 */
class ProductResource extends Resource
{
    protected static ?string $model = Product::class;
    protected static ?string $navigationIcon = 'heroicon-o-shopping-bag';
    protected static ?string $navigationGroup = 'Catalog';
    protected static ?int $navigationSort = 1;

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Tabs::make('Product')
                ->tabs([
                    // === General Tab ===
                    Forms\Components\Tabs\Tab::make('General')->schema([
                        Forms\Components\TextInput::make('sku')
                            ->required()
                            ->unique(ignoreRecord: true)
                            ->label('SKU'),
                        Forms\Components\TextInput::make('model')
                            ->label('Model'),
                        Forms\Components\TextInput::make('image')
                            ->label('Image Path'),
                        Forms\Components\Toggle::make('status')
                            ->default(true),
                        Forms\Components\Toggle::make('featured')
                            ->default(false),
                        Forms\Components\TextInput::make('sort_order')
                            ->numeric()
                            ->default(0),
                    ])->columns(2),

                    // === Pricing Tab ===
                    Forms\Components\Tabs\Tab::make('Pricing')->schema([
                        Forms\Components\TextInput::make('price')
                            ->numeric()
                            ->prefix('$')
                            ->required(),
                        Forms\Components\TextInput::make('cost')
                            ->numeric()
                            ->prefix('$'),
                        Forms\Components\TextInput::make('quantity')
                            ->numeric()
                            ->default(0),
                        Forms\Components\Toggle::make('subtract')
                            ->default(true)
                            ->label('Subtract Stock'),
                        Forms\Components\TextInput::make('minimum')
                            ->numeric()
                            ->default(1)
                            ->label('Minimum Quantity'),
                    ])->columns(2),

                    // === Descriptions Tab (per language) ===
                    Forms\Components\Tabs\Tab::make('Descriptions')->schema([
                        Forms\Components\Repeater::make('descriptions')
                            ->relationship('descriptions')
                            ->schema([
                                Forms\Components\Select::make('language_id')
                                    ->relationship('language', 'name')
                                    ->required(),
                                Forms\Components\TextInput::make('title')
                                    ->required(),
                                Forms\Components\Textarea::make('description')
                                    ->rows(5),
                                Forms\Components\TextInput::make('seo_title'),
                                Forms\Components\Textarea::make('meta_description'),
                                Forms\Components\TextInput::make('meta_keywords'),
                            ])
                            ->columns(2)
                            ->label('Descriptions by Language'),
                    ]),

                    // === Categories Tab ===
                    Forms\Components\Tabs\Tab::make('Categories')->schema([
                        Forms\Components\Select::make('categories')
                            ->relationship('categories', 'id')
                            ->multiple()
                            ->label('Categories'),
                    ]),

                    // === Store Assignment Tab ===
                    Forms\Components\Tabs\Tab::make('Stores')->schema([
                        Forms\Components\Select::make('stores')
                            ->relationship('stores', 'name')
                            ->multiple()
                            ->label('Stores'),
                    ]),

                    // === SEO Tab ===
                    Forms\Components\Tabs\Tab::make('SEO')->schema([
                        Forms\Components\Placeholder::make('seo_hint')
                            ->content('SEO URLs are managed per language via the Descriptions tab.'),
                    ]),
                ])
                ->columnSpanFull(),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('sku')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('model')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('price')->money('USD')->sortable(),
                Tables\Columns\TextColumn::make('quantity')->sortable(),
                Tables\Columns\IconColumn::make('status')->boolean(),
                Tables\Columns\IconColumn::make('featured')->boolean(),
                Tables\Columns\TextColumn::make('updated_at')->dateTime()->sortable(),
            ])
            ->filters([
                Tables\Filters\TernaryFilter::make('status'),
                Tables\Filters\TernaryFilter::make('featured'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListProducts::route('/'),
            'create' => Pages\CreateProduct::route('/create'),
            'edit' => Pages\EditProduct::route('/{record}/edit'),
        ];
    }
}
